sudo: required
services:
- docker
language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
before_install:
- openssl aes-256-cbc -K $encrypted_4917fba71c1e_key -iv $encrypted_4917fba71c1e_iv
  -in franleplant.com.pem.enc -out franleplant.com.pem -d
- docker build -t franleplant/blog .
- docker run -d -p 8080:8000/tcp blog
- docker ps -a
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push franleplant/blog;
  ssh -i franleplant.com.pem "$AWS_USER"@"$AWS_HOST" -t "sudo docker run -d -p 80:8000 franleplant/blog"
  fi
