sudo: required
services:
- docker
language: rust
rust:
- stable
matrix:
  allow_failures:
  - rust: nightly
before_install:
- openssl aes-256-cbc -K $encrypted_4917fba71c1e_key -iv $encrypted_4917fba71c1e_iv
  -in franleplant.com.pem.enc -out franleplant.com.pem -d
- sudo chmod 400 franleplant.com.pem
- docker build -t "$DOCKER_BUILD_NAME" .
- docker run -d -p 8080:8000/tcp "$DOCKER_BUILD_NAME"
- docker ps -a
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push "$DOCKER_BUILD_NAME";
  ssh -o "StrictHostKeyChecking no" -i franleplant.com.pem "$AWS_USER"@"$AWS_HOST" -t "sudo docker stop $DOCKER_BUILD_NAME; sudo docker rm $DOCKER_BUILD_NAME; sudo docker pull $DOCKER_BUILD_NAME; sudo docker run -d -p 80:8000 --name $DOCKER_BUILD_NAME $DOCKER_BUILD_NAME;";
  fi
